# ---- Build / daemon tuning ----
org.gradle.jvmargs=-Xmx3g -XX:MaxMetaspaceSize=1g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.workers.max=4

# ---- AndroidX ----
android.useAndroidX=true

# ---- Kotlin ----
kotlin.code.style=official

# ---- AGP ----
android.nonTransitiveRClass=true